/* Net WAIS_v_7 - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include "net_types.h"


int trace_control = TRACE_CONT_RUN;

extern void httpServer_init();
extern void httpServer_getRequest();
extern void httpServer_sendResponse();
extern void httpServer_disconnectClient();
extern void httpServer_checkBreakPoints();
extern void httpServer_finish();

static WAIS_v_7_NetMarking marking;
static WAIS_v_7_InputSignals inputs, prev_inputs;
static WAIS_v_7_PlaceOutputSignals place_out;
static WAIS_v_7_EventOutputSignals ev_out;

void setup()
{
    createInitial_WAIS_v_7_NetMarking( &marking );
    init_WAIS_v_7_OutputSignals( &place_out, &ev_out );
    WAIS_v_7_InitializeIO();
    WAIS_v_7_GetInputSignals( &prev_inputs, NULL );
#ifdef HTTP_SERVER
    httpServer_init();
#endif
}

void loop()
{
#ifdef HTTP_SERVER
    httpServer_getRequest();
#endif

    if( trace_control != TRACE_PAUSE )
        WAIS_v_7_ExecutionStep( &marking, &inputs, &prev_inputs, &place_out, &ev_out );
    else WAIS_v_7_GetInputSignals( &inputs, NULL );
    if( trace_control > TRACE_PAUSE ) --trace_control;

#ifdef HTTP_SERVER
    httpServer_sendResponse();
#endif

    WAIS_v_7_LoopDelay();

#ifdef HTTP_SERVER
    httpServer_disconnectClient();
    httpServer_checkBreakPoints();
#endif
}

#ifndef ARDUINO
int main()
{
    setup();

    do loop();
    while( WAIS_v_7_FinishExecution( &marking ) == 0 );

#ifdef HTTP_SERVER
    httpServer_finish();
#endif

    return 0;
}
#endif


WAIS_v_7_NetMarking* get_WAIS_v_7_NetMarking()
{
    return &marking;
}

WAIS_v_7_InputSignals* get_WAIS_v_7_InputSignals()
{
    return &inputs;
}

WAIS_v_7_PlaceOutputSignals* get_WAIS_v_7_PlaceOutputSignals()
{
    return &place_out;
}

WAIS_v_7_EventOutputSignals* get_WAIS_v_7_EventOutputSignals()
{
    return &ev_out;
}

