/* Net WAIS_v_7 - IOPT */
/* Automatic code generated by IOPT2C XSLT transformation. */


#include <stdlib.h>
#include <string.h>
#include "net_types.h"


static WAIS_v_7_TransitionFiring tfired;
    

void WAIS_v_7_ExecutionStep(
     WAIS_v_7_NetMarking *prev_marking,
     WAIS_v_7_InputSignals *inputs,
     WAIS_v_7_InputSignals *prev_in,
     WAIS_v_7_PlaceOutputSignals *place_out,
     WAIS_v_7_EventOutputSignals *ev_out )
{
    WAIS_v_7_NetMarking add_marking;
    WAIS_v_7_NetMarking avail_marking = *prev_marking;
    WAIS_v_7_InputSignalEvents input_events;
    WAIS_v_7_OutputSignalEvents output_events;

    memset( &output_events, 0, sizeof(output_events) );
    memset( &tfired, 0, sizeof(tfired) );

    createEmpty_WAIS_v_7_NetMarking( &add_marking );
    WAIS_v_7_GetInputSignals( inputs, &input_events );
    WAIS_v_7_GenerateInputSignalEvents( prev_in, inputs, &input_events );
    *prev_in = *inputs;

    /* Transition Start Irrigation */
    if( t_2_enabled( prev_marking, &avail_marking ) &&
        t_2_events( &input_events ) &&
        t_2_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_2 = 1;
        t_2_remove_marks( &avail_marking );
        t_2_add_marks( &add_marking );
        t_2_generate_output_events( &output_events );
    }

    /* Transition Stop Irrigation */
    if( t_3_enabled( prev_marking, &avail_marking ) &&
        t_3_events( &input_events ) &&
        t_3_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_3 = 1;
        t_3_remove_marks( &avail_marking );
        t_3_add_marks( &add_marking );
        t_3_generate_output_events( &output_events );
    }

    /* Transition Verify if rain < 30% */
    if( t_6_enabled( prev_marking, &avail_marking ) &&
        t_6_events( &input_events ) &&
        t_6_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_6 = 1;
        t_6_remove_marks( &avail_marking );
        t_6_add_marks( &add_marking );
        t_6_generate_output_events( &output_events );
    }

    /* Transition Verify Soil Humidity < 30% */
    if( t_7_enabled( prev_marking, &avail_marking ) &&
        t_7_events( &input_events ) &&
        t_7_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_7 = 1;
        t_7_remove_marks( &avail_marking );
        t_7_add_marks( &add_marking );
        t_7_generate_output_events( &output_events );
    }

    /* Transition Verify if Rain >= 30% */
    if( t_19_enabled( prev_marking, &avail_marking ) &&
        t_19_events( &input_events ) &&
        t_19_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_19 = 1;
        t_19_remove_marks( &avail_marking );
        t_19_add_marks( &add_marking );
        t_19_generate_output_events( &output_events );
    }

    /* Transition Verify Soil Humidity >= 30% */
    if( t_20_enabled( prev_marking, &avail_marking ) &&
        t_20_events( &input_events ) &&
        t_20_guards( prev_marking, inputs, place_out, ev_out ) ) {
        tfired.t_20 = 1;
        t_20_remove_marks( &avail_marking );
        t_20_add_marks( &add_marking );
        t_20_generate_output_events( &output_events );
    }

    add_WAIS_v_7_NetMarkings( &avail_marking, &add_marking );

    WAIS_v_7_GenerateTransitionActionOutputSignals( &tfired, &avail_marking, ev_out );
    WAIS_v_7_GeneratePlaceOutputSignals( &avail_marking, inputs, place_out, ev_out );
    WAIS_v_7_GenerateEventOutputSignals( &output_events, ev_out );
    WAIS_v_7_PutOutputSignals( place_out, ev_out, &output_events );
    *prev_marking = avail_marking;
}

WAIS_v_7_TransitionFiring* get_WAIS_v_7_TransitionFiring()
{
    return &tfired;
}

